name: Signing (deno)
on: [push, pull_request]
jobs:
  Signing:
    strategy:
      matrix:
        deno: [ '1.17.2' ]
        os: [ 'ubuntu-20.04' ]
    runs-on: ${{ matrix.os }}
    name: 'Signing | deno ${{ matrix.deno }}'
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - run: cd signing/deno && pwd && deno test index.ts
